import Header from '@/components/header'
import {GoogleTagManager} from '@next/third-parties/google'
import clsx from 'clsx'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Head from 'next/head'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return <html lang="en">
    <Head>
      <GoogleTagManager gtmId="GTM-TKVK2RCD" />
    </Head>
    <body
      className={
        clsx([
          `${geistSans.variable} ${geistMono.variable} antialiased`,
          // max-w-7xl: best practice for container
          // grid-rows-[auto_auto_1fr_auto]: 4 rows
          'grid min-h-dvh grid-rows-[auto_auto_1fr_auto]',
          'bg-light dark:bg-dark text-dark dark:text-light text-lg'
        ])}>
      <Header />
      <main>
        {children}
      </main>
      <a>footer</a>
    </body>
  </html>
}
